[versions]
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
activity = "1.8.0"
constraintlayout = "2.1.4"
material = "1.11.0"
appcompat = "1.6.1"

# Navigation
navigation = "2.7.7"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
# Navigation
navigation-fragment  = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation"}
navigation-ui  = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation"}


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-kapt = {id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin"}
